#!/usr/bin/env python
"""
Forked from https://github.com/cbrueffer/pep8-git-hook/blob/master/pre-commit
Origin from https://gist.github.com/810399
"""

from __future__ import with_statement, print_function
import os
import re
import shutil
import subprocess
import sys
import tempfile


# Don't fill in both of these
select_codes = []
ignore_codes = ["E121", "E122", "E123", "E124", "E125", "E126",
                "E127", "E128", "E129", "E131", "E501", ]

overrides = ["--max-line-length=119"]


def system(*args, **kwargs):
    kwargs.setdefault('stdout', subprocess.PIPE)
    proc = subprocess.Popen(args, **kwargs)
    out, err = proc.communicate()
    return out


def main():
    modified = re.compile('^[AM]+\s+(?P<name>.*\.py)', re.MULTILINE)
    files = system('git', 'status', '--porcelain').decode("utf-8")
    modified_files = modified.findall(files)

    tempdir = tempfile.mkdtemp()
    for file_name in modified_files:
        file_path = os.path.join(tempdir, file_name)
        path = os.path.dirname(file_path)

        if not os.path.exists(path):
            os.makedirs(path)
        with open(file_path, 'w') as f:
            system('git', 'show', ':' + file_name, stdout=f)

    args = ['pep8']
    if select_codes and ignore_codes:
        print(u'Error: select and ignore codes are mutually exclusive')
        sys.exit(1)
    elif select_codes:
        args.extend(('--select', ','.join(select_codes)))
    elif ignore_codes:
        args.extend(('--ignore', ','.join(ignore_codes)))
    args.extend(overrides)
    args.append('.')

    output = system(*args, cwd=tempdir)
    shutil.rmtree(tempdir)

    if output:
        print(u'PEP8 style violations have been detected.',
              'Please fix them or force the commit with:',
              '"git commit --no-verify".', sep='\n', end='\n\n')
        print(output.decode("utf-8"),)
        sys.exit(1)


if __name__ == '__main__':
    main()
